export const ResponseMessages = {
    CREATE_SUCCESS: "Created successfully!",
    CREATE_FAIL: "Failed to create",
    DUPLICATE_FOUND: "Already Exist",
    UPDATE_SUCCESS: "Updated successfully!",
    UPDATE_FAIL: "Failed to update",
    DELETE_SUCCESS: "Deleted successfully!",
    DELETE_FAIL: "Failed to delete",
    FETCH_SUCCESS: "Fetched successfully!",
    FETCH_FAIL: "Failed to fetch",
    NOT_FOUND: "Not found!",
    USER_EXIST: "User Exists!",
    USER_NOT_EXIST: "User Doesn't Exist!",
    SERVER_ERROR: "Internal server error",
    TOKEN_EXPIRED: "Token expired!",
    UNAUTHORIZED_MESSAGE: "Unauthorized!",
    BAD_REQUEST: "Fill out the necessary details!",
    WRONG_CREDENTIALS: "Wrong Credentials!",
    USER_LOG_OUT: "User Logged out!",
    WRONG_REFRESH_TOKEN: "Refresh Token Expired or Not Valid!",
    ACCESS_TOKEN_REFRESH: "Access Token Refreshed Successfully",
    OTP_SENT: "OTP sent",
    PASSWORD_RESET: "Password Reset Successfully!"
};
