export const statusCode = {
    CREATE_SUCCESS_CODE: 201,
    FETCH_SUCCESS_CODE: 200,
    NOT_FOUND_CODE: 404,
    DUPLICATE_CODE: 409,
    BAD_REQUEST_CODE: 400,
    FORBIDDEN_CODE: 403,
    UNAUTHORIZED_CODE: 401,
    UNPROCESSED_ENTITY_CODE: 422,
    SERVER_ERROR_CODE: 500,
    NO_CONTENT_CODE: 204,
};